{% set version = "5.1.0" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/traits/traits-{{ version }}.tar.gz
  sha256: af91b481d24cc6f47791f48c3b50c5190f460b7727d30656a780dff894ee63f6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - traits

about:
  home: http://code.enthought.com/projects/traits
  license: BSD 3-clause
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
