{% set version = "5.1.2" %}

package:
  name: traits
  version: {{ version }}

source:
  fn: traits-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/traits/traits-{{ version }}.tar.gz
  sha256: 7a78594f84dd81486cd876fdfe3648583836377cb9fb02973f307dc06fc52728

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - traits

about:
  home: http://code.enthought.com/projects/traits
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: traits - explicitly typed attributes for Python

extra:
  recipe-maintainers:
    - grlee77
