appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gb/liQ64vIHtBNtORNt7zBabndWZflXAcacPHWWyIsmIy2ssisaHS6WxxhbQdRg8tp3192hz+ccr/HVkMpOlwFdBlL7NPAXFVK3Fctp4AbWwNWmvQcknoi3YSe5yER6OB61iNi7DmrIEsV/5UDCVg8I4+qWcoPHjQ5xs5UYOPHEHosFFJnDu9rZMzQS1RxfC4eEu+OLZV3usNfgO04NezmXUi1KXaWbQgpqNMrnozphz2mzTjU+igusS6Dh1ZAjRmZ26gvHNk6kpRk9IiY4m9H39a8NM91yMAGULP6bLlujWBEjdDarr+rzAvq9rD3VRNGZZtageRR00Mn/sHJfY3Nntp+5oKKg6Mr/Ia2ixqUymg1+Iw+pRL/E8jgCmIZNhSMkVRmvOIgD0GCtJdez4gQIgn81O7J989M/UX31GoQNdQ49n+pkJn0dzI2GXp46J7BcVdnD4GeWcvSslPx61vqv6rKbKFEaalSxhwaVaLrI6NmZvtEM/xl02vjK1iQOjdmHSujZaz2nNnrbN+fRVFVYJWPENZC0UfhN8DAwsNgkU2SVcVOcN/GGEC2z5kQo93FhQUKdqUXAhEDKVhfD2KnlQHwCn9JgQG6kRFu4dqDK1QE5VA5vK0NuO/cdFLrzwjYjIzl5YnCxN5bUZytvSYDr9nBrBcJCCmSbUgkctNSQ=}
