travis:
  secure:
    BINSTAR_TOKEN: R30mxWkTrZHCyvg2HF4dAX9hDAycGfnJWAsGS/7ywoFVejxE8r3hFH/Lytzw+q4bpXMWisw4JU4UP+mbxcsCILIMq2Hp91e5Objhl5n+rh/KoZ3PGTMyGn96f5L0/v5T7N6bvL5CEK2BK0ieOiRPCk86rdGkBSFOap/S6jT7nPSVmxpxwyiNzAN/OU1husWemV/g8ZSJz2g/pvSFhv1atwsVQ7u2IvNK4z7GuQMhnEd+HvQQHx1/lLxKW2Gt1MX2MEfclmxwU6Fgpeu2Fhi0cieC45vAgvq8YxzJ0Sg4Gu7iNZomE/3Ifw/hsV2d8urp5kyiqPC1kJMq8du10fHRv9yVmIt8iPRArZml2cMRRjvHeE26MSkXR9sYE838R9OHIOht6Z2c9VJmAWl6m9qMLnxwIDhku959xLwbDFUrrSwmVEkDIzGQpkPzGoYxs8zZ/lFEq8GB+2m5JupyG1T8wNeu5E5xP0NswZzPUu3ZcmGC58h8P952c/O1A2RdhEK9myYG8JMLQ0B4TEIq4+/ydPhrA65ziQr4nOwabQjKqpVvC7wGZlpFQjZn8U2rc83+/tUQIEul2hdAcW4abw8P+W+8ix8GyXt/QrQKw/cmHiCCiioTzHodZq56L9MLo+rHVjOFLgcp5oE3ATaudHWbRfnRGqmhHLzaL+fQ8ADFHZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
