travis:
  secure:
    BINSTAR_TOKEN: IcBXHScDbRVO+21NgXJZDGwW6gzNZrOrdx4U+Y9gAqb4UffV9BWoiVlCbH2/6aymF26AGx5axiYGOlCExXYos4MGPGyaEBPNVr/zQJHeVjuxWT+SPtyTBlXenRSJNZGjiXe+Bj9lk5Vds+rQ58I/KnKj2f7hGl+BEUhfN5PdYdi4+9bbjWd1AdxLh2pcCKQnwGHmetwzc7liU+2St2M981tn0L7KChBx1hQCpnlMBzwYL0QtauFsX3T2djWngLuwtRs8XJJ/rGKvp1u0g95GZ8va44e0poAD3hMiPpY7sTmTT4BOqbzAyibJRrc3pccyLPguh2Nv3CLZugeMA72OehOvani1amVDSgySkSt4g1rltBvEqDPWz40Rc72NRTeAtsEgp9AZFBFxitaRr4g/DTBIlIvIA0Xd/vPp7S8+P0LI1WtHJDRu25od7pTWU86dYPt/bPNdDXcYMeOT4zpekcEw0DbwNiauuvQU2oo2MSPEjvOe52ZCyHOidXT61cZ1tWadRigx5C+I1vP97egwPrMG7lTKNqpL8mY0D3a00u2uXKFMuocjiolcwkCl0902YT3nzo1A/jjDq5SvPdeogCCKs3nit6xYNuLrXkgBM6KiFuNDGP7JJ9XXIQkM8Noaydhi4vatxzzLGIGG+EAx1oWeV7JhcRWJmFy77lXPEq0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
